# Generated by Django 5.2.8 on 2026-03-28 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0003_link_description_link_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='transmition',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='link',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='recruter',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='recruter',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.AlterUniqueTogether(
            name='testscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testscore',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transmition',
            name='leaders',
        ),
        migrations.RemoveField(
            model_name='transmition',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='link',
            name='title',
        ),
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.tagportfolio'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Recruter',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestScore',
        ),
        migrations.DeleteModel(
            name='Transmition',
        ),
    ]
