# Generated by Django 5.2.8 on 2026-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_remove_comment_author_remove_comment_transmition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
