# Generated by Django 5.2.8 on 2026-01-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_alter_offersjobuser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='course',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='business',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offersjob',
            name='hr',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='testscore',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='number_house',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='street',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='QuestionnaireCategory',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestScore',
        ),
    ]
