# Generated by Django 4.2.1 on 2025-07-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0004_skills_questionnaire_hobby_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='name',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='user',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workapp.questionnairecategory'),
        ),
    ]
