# Generated by Django 4.2.1 on 2025-07-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_questionnairecategory_remove_questionnaire_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='user',
        ),
    ]
