# Generated by Django 4.2.1 on 2025-07-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_questionnaire_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='user',
        ),
    ]
