# Generated by Django 5.2.8 on 2026-01-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
